name: bcpbooster
description: An app to log signups for Bellarmine College Prep's Booster Club

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'


version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  date_format: ^1.0.8
  email_validator: ^1.0.4
  flutter_auth_buttons: ^0.6.0
  google_sign_in: ^4.1.1
  http: ^0.12.0+4
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
