name: bcpbooster
description: An app to log signups for Bellarmine College Prep's Booster Club

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'


version: 1.0.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  date_format: ^2.0.6
  email_validator: ^2.0.1
  firebase_analytics: ^9.1.9
  firebase_core: ^1.17.1
  flutter_signin_button: ^2.0.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.2
  http: ^0.13.4
  modal_progress_hud_nsn: ^0.2.1
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
